### ISSUE TITLE
[Enhancement] 회원 관리 기능 구현

### ISSUE THREAD

**Issue by fredlee613** [moadata-test/moadata-server#3]
## Decription
기본적인 회원 관리 기능 구현
***
## Todo List
- [x] 회원 기본 CRUD 기능 구현
- [x] 회원 가입 시 이메일 중복 검증
- [x] 회원 가입 시 이메일 검증
***
## 참고사항
